# The pull request's title should be fulfilled the following pattern:
#
#     <type>[optional scope]: <description>
#
# ... where valid types and scopes can be found below; for example:
#
#     fix(test): flaky test V1_ProxyAuthenticationTest.anonymousSocketTest
#
# More about configurations on https://github.com/Ezard/semantic-prs#configuration

enabled: true

titleOnly: true

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert

targetUrl: https://github.com/korandoru/zeronos/blob/master/.github/semantic.yml
