name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '4 2 * * *'

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` event
#   github.event.number: set to the number of the pull request if `pull_request` event
#   github.run_id: otherwise, it's a `push` or `schedule` event, only cancel if we rerun the workflow
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    if: (github.event_name != 'schedule') || (github.repository == 'korandoru/zeronos')
    name: Check and lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Check license header
        uses: korandoru/hawkeye@main
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check code style
        run: ./mvnw spotless:check

  unittest:
    if: (github.event_name != 'schedule') || (github.repository == 'korandoru/zeronos')
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Maven verify
        run: ./mvnw clean verify

  required:
    name: Required
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ always() && ((github.event_name != 'schedule') || (github.repository == 'korandoru/zeronos')) }}
    needs: [ check, unittest ]
    steps:
      - name: Guardian
        run: |
          if [[ ! ( \
                 "${{ needs.unittest.result }}" == "success" \
              && "${{ needs.check.result }}" == "success" \
              ) ]]; then
            echo "Required jobs haven't been completed successfully."
            exit -1
          fi
